name: Test pull_request

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    outputs:
      image: ${{ steps.build-push.outputs.image}}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: |
          go get golang.org/x/lint/golint
          golint ./...
      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v0.8.3/ko_0.8.3_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Publish docker image
        id: build-push
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        run: |
          IMAGE=$(./ko publish -B -L .)
          echo ::set-output name=image::${IMAGE}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: deploy to kind
        run: |
          kind load --name chart-testing docker-image ${{steps.build-push.outputs.image}}
          helm install simpleapp ./chart/azure-federated-actions --set image.name=${{steps.build-push.outputs.image}}
          kubectl wait --for=condition=available --timeout=60s deployment/simpleapp-azure-federated-actions
          sleep 5
          helm test simpleapp --logs